export const FETCH_MANGA = "FETCH_MANGA";
export const FETCH_ALL_MANGA = "FETCH_ALL_MANGA";
export const GET_MANGA_INFO = "GET_MANGA_INFO";
export const GET_USER_UPLOADED_MANGA = "GET_USER_UPLOADED_MANGA";

